name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew
    - name: Update
      run: sudo apt update && sudo apt upgrade -y
    - name: Download dependencies
      run: sudo apt install automake ant autopoint cmake build-essential libtool-bin patch pkg-config protobuf-compiler ragel subversion unzip git openjdk-8-jre openjdk-8-jdk flex python3 wget
    - name: Get Android NDK
      run: wget https://dl.google.com/android/repository/android-ndk-r27-linux.zip
    - name: Extract Android NDK
      run: unzip android-ndk-r27-linux.zip -d ./
    - name: Set the NDK eviornment variable
      run: export ANDROID_NDK=./android-ndk-r27
    - name: Download Android SDK
      run: wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
    - name: Make Driectory for SDK
      run: mkdir ./sdk
    - name: Extract Android SDK
      run: unzip commandlinetools-linux-*.zip -d ./sdk
    - name: Set the SDK eviornment variable
      run: export ANDROID_SDK=./sdk
    - name: Test env vars
      run: echo $ANDROID_NDK
    - name: Test env vars
      run: echo $ANDROID_SDK
    - name: Build app
      run: buildsystem/compile.sh -l --release -a arm64
