name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # - name: Grant execute permission for gradlew
    #   run: chmod +x gradlew
    - name: Update
      run: sudo apt update && sudo apt upgrade -y
    - name: Download dependencies
      run: sudo apt install automake ant autopoint cmake build-essential libtool-bin patch pkg-config protobuf-compiler ragel subversion unzip git openjdk-8-jre openjdk-8-jdk flex python wget
    - name: Build app
      run: buildsystem/compile.sh -l -r -a arm64
